[tool.ruff]
select = ["E", "F", "I"]
line-length = 320
fix = true
unsafe-fixes = true
ignore = ["E741", "E742", "E743", "E702"]
exclude = ["examples", "figures", "jupyter", "latex", "__pycache__"]


[tool.ruff.isort]
# Combine imports from the same module (e.g., "from x import a, b")
combine-as-imports = true

# Keep all imports together (no blank lines between stdlib, third-party, local)
no-sections = true

# Donâ€™t leave blank lines between different import types
lines-between-types = 0

# Sort imports alphabetically within their section
force-sort-within-sections = true

# Optionally detect local imports by your package name
known-first-party = ["my_project"]


