name: cpb
channels:
  - conda-forge
dependencies:
  - python=3.11
  - wget
  - git
  - pip
  - pip:
      - numpy
      - scipy
      - matplotlib
      - vtk
      - pandas
      - pybind11[global]
      - setuptools
      - ipython
      - ipykernel
      - pytest
